name: solar system workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

jobs:
    unit-testing:
        name: unit-testing
        runs-on: ubuntu-latest
        steps:
            - name: Cheakout Repository
              uses: actions/checkout@v4
            # Debug repository structure
            - name: Check Repository Files
              run: |
                pwd
                ls -la
                find . -maxdepth 2  
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 24
            - name: Install Dependencies
              run: npm install
            - name: Unit Testing
              run: npm test
            - name: Run Application
              run: node index.js
            - name: Archive Test Result
              uses: actions/upload-artifact@v4
              with:
                name: Mocha-Test-Result
                path: test-result.xml      