name: solar system workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'           

jobs:
    unit-testing:
        name: unit-testing
        runs-on: ubuntu-latest

        env:
         MONGO_URI: ${{ secrets.MONGO_URI }}

        steps:
            - name: Cheakout Repository
              uses: actions/checkout@v4 
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm install
            - name: Unit Testing
              run: npm test