name: solar system workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  unit-testing:
    name: unit-testing
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Unit Testing
        run: npm test

      - name: Verify Test Report
        run: |
          pwd
          ls -la
          find . -name "*.xml"

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result
          path: test-results.xml
          if-no-files-found: warn

  code-coverage:
    name: Code Coverage
    needs: unit-testing
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check Code Coverage
        continue-on-error: true
        run: npm run coverage

      - name: Verify Coverage Report
        run: |
          ls -la
          ls -la coverage || true

      - name: Archive Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-result
          path: coverage
          retention-days: 5
          if-no-files-found: warn